### ISSUE TITLE
Fusion Start Loop

### ISSUE THREAD

**Issue by 0xhexdec** [0xhexdec/S3DtoFusion#1]
Something seems to trigger a start loop of multiple instances of Fusion360, I don't know where this is coming from and i try to investigate the problem.

**Comment by CLJ1979** [comment]
It seems to come from an error when installing numpy in `utils/__init__.py`. Apparently pip isn't available (at least on my Mac) and I had to run `python -m ensurepip --upgrade` before installing numpy.

**Comment by 0xhexdec** [comment]
I suspect it is the same problem I had with windows. As Fusion ships with its own python interpreter, burried deep inside the folder structure, I had to extract that path to use Fusion's Python and its pip instance. I did this for windows but not for Mac (no access to Mac at that time) maybe I will try to fix that in the near future. I will open an issue for Mac explicitly.
